/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

/**
 *
 * @author Daniel Huenul
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Submenu_salirPorgrama = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Submenu_GestionarLibro = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        Submenu_GestionarEstado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Submenu_editoriales = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Submenu_Autores = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        submenu_idioma = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Submenu_trabajadores = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Submenu_clientes = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        submenu_distribuidores = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        submenu_direcciones = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        submenu_telefonos = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Submenu_correos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        submenu_arriendos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        submenu_ventas = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        submenu_boleta = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        submenu_mediopago = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        submenu_compras = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        submenu_facturas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo.png"))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ajustes.png"))); // NOI18N
        jMenu1.setText("Opciones");

        Submenu_salirPorgrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        Submenu_salirPorgrama.setText("Salir");
        jMenu1.add(Submenu_salirPorgrama);

        BarraMenu.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/libros.png"))); // NOI18N
        jMenu2.setText("Libro");

        Submenu_GestionarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/libros.png"))); // NOI18N
        Submenu_GestionarLibro.setText("Gestionar libro");
        jMenu2.add(Submenu_GestionarLibro);
        jMenu2.add(jSeparator8);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/infoPersonal.png"))); // NOI18N
        jMenu3.setText("Detalle");

        Submenu_GestionarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estado.png"))); // NOI18N
        Submenu_GestionarEstado.setText("Gestionar Estados");
        jMenu3.add(Submenu_GestionarEstado);
        jMenu3.add(jSeparator1);

        Submenu_editoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editorial.png"))); // NOI18N
        Submenu_editoriales.setText("Gestionar Editoriales");
        jMenu3.add(Submenu_editoriales);
        jMenu3.add(jSeparator2);

        Submenu_Autores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/autor.png"))); // NOI18N
        Submenu_Autores.setText("Gestionar Autores");
        jMenu3.add(Submenu_Autores);
        jMenu3.add(jSeparator3);

        submenu_idioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/idioma.png"))); // NOI18N
        submenu_idioma.setText("Gestionar idiomas");
        jMenu3.add(submenu_idioma);

        jMenu2.add(jMenu3);

        BarraMenu.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trabajadores.png"))); // NOI18N
        jMenu4.setText("Personas");

        Submenu_trabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trabajador.png"))); // NOI18N
        Submenu_trabajadores.setText("Gestionar trabajadores");
        jMenu4.add(Submenu_trabajadores);
        jMenu4.add(jSeparator4);

        Submenu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente.png"))); // NOI18N
        Submenu_clientes.setText("Gestionar clientes");
        jMenu4.add(Submenu_clientes);
        jMenu4.add(jSeparator5);

        submenu_distribuidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/distri.png"))); // NOI18N
        submenu_distribuidores.setText("Gestionar distribuidores");
        jMenu4.add(submenu_distribuidores);
        jMenu4.add(jSeparator6);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agenda.png"))); // NOI18N
        jMenu5.setText("Gestionar datos");

        submenu_direcciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mapaa.png"))); // NOI18N
        submenu_direcciones.setText("Gestionar direcciones");
        jMenu5.add(submenu_direcciones);
        jMenu5.add(jSeparator7);

        submenu_telefonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agenda.png"))); // NOI18N
        submenu_telefonos.setText("Gestionar N° telefonicos");
        jMenu5.add(submenu_telefonos);
        jMenu5.add(jSeparator9);

        Submenu_correos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mail.png"))); // NOI18N
        Submenu_correos.setText("Gestionar Correos");
        jMenu5.add(Submenu_correos);

        jMenu4.add(jMenu5);

        BarraMenu.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/transferir.png"))); // NOI18N
        jMenu6.setText("Arriendos");

        submenu_arriendos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/transferir.png"))); // NOI18N
        submenu_arriendos.setText("Gestionar Arriendos");
        jMenu6.add(submenu_arriendos);

        BarraMenu.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta.png"))); // NOI18N
        jMenu7.setText("Ventas");

        submenu_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta.png"))); // NOI18N
        submenu_ventas.setText("Gestionar ventas");
        jMenu7.add(submenu_ventas);
        jMenu7.add(jSeparator10);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/infoPersonal.png"))); // NOI18N
        jMenu8.setText("Detalles");

        submenu_boleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boleta.png"))); // NOI18N
        submenu_boleta.setText("Gestionar boletas");
        jMenu8.add(submenu_boleta);
        jMenu8.add(jSeparator11);

        submenu_mediopago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/metodos.png"))); // NOI18N
        submenu_mediopago.setText("Gestionar medios de pago");
        jMenu8.add(submenu_mediopago);

        jMenu7.add(jMenu8);

        BarraMenu.add(jMenu7);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compra.png"))); // NOI18N
        jMenu9.setText("Compras");

        submenu_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compra.png"))); // NOI18N
        submenu_compras.setText("Gestionar compras");
        jMenu9.add(submenu_compras);
        jMenu9.add(jSeparator12);

        submenu_facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/factura.png"))); // NOI18N
        submenu_facturas.setText("Gestionar facturas");
        jMenu9.add(submenu_facturas);

        BarraMenu.add(jMenu9);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    public javax.swing.JMenuItem Submenu_Autores;
    public javax.swing.JMenuItem Submenu_GestionarEstado;
    public javax.swing.JMenuItem Submenu_GestionarLibro;
    public javax.swing.JMenuItem Submenu_clientes;
    public javax.swing.JMenuItem Submenu_correos;
    public javax.swing.JMenuItem Submenu_editoriales;
    public javax.swing.JMenuItem Submenu_salirPorgrama;
    public javax.swing.JMenuItem Submenu_trabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    public javax.swing.JMenuItem submenu_arriendos;
    public javax.swing.JMenuItem submenu_boleta;
    public javax.swing.JMenuItem submenu_compras;
    public javax.swing.JMenuItem submenu_direcciones;
    public javax.swing.JMenuItem submenu_distribuidores;
    public javax.swing.JMenuItem submenu_facturas;
    public javax.swing.JMenuItem submenu_idioma;
    public javax.swing.JMenuItem submenu_mediopago;
    public javax.swing.JMenuItem submenu_telefonos;
    public javax.swing.JMenuItem submenu_ventas;
    // End of variables declaration//GEN-END:variables
}
